---
apiVersion: v1
kind: Namespace
metadata:
  name: ztp-clusters-{{ '%02d' | format(item) }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ztp-clusters-{{ '%02d' | format(item) }}
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: ztp-clusters-{{ '%02d' | format(item) }}
  project: ztp-app-project
  source:
    path:  telco-ran/configuration/argocd/cluster/ztp-clusters-{{ '%02d' | format(item) }}
    repoURL: http://{{ gogs_username }}:{{ gogs_password }}@{{ gogs_host }}:{{ gogs_port }}/testadmin/telco-reference.git
    targetRevision: {{ telco_reference_branch }}
  ignoreDifferences: # recommended way to allow ACM controller to manage its fields. alternative approach documented below (1)
  - group: cluster.open-cluster-management.io
    kind: ManagedCluster
    managedFieldsManagers:
    - controller
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=background
    - RespectIgnoreDifferences=true
